version: "2"
services:
  go-facebook:
    # restart: always
    extends:
      file: base.yml
      service: go
    expose:
      - 8080
    ports:
      - 80:8080
      - 443:8080
    volumes:
      - ../:/go/src
    working_dir: /go/src
    # command: sleep 7200
networks:
  default:
    external:
      name: sandbox_network
